---

- name: "CURL | Ensure Debian dependencies are installed"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - libcurl4-openssl-dev
    - make
    - tar
  when: '"{{ ansible_os_family }}" == "Debian"'

- name: "CURL | Ensure RedHat dependencies are installed"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make
    - tar
  when: '"{{ ansible_os_family }}" == "RedHat"'