---

- name: "CURL | Include tasks to install from source"
  include: "source.yml"
  when: curl_buildfromsource|bool == true

- name: "CURL | Include tasks to install from packaged sources"
  include: "packages.yml"
  when: curl_buildfromsource|bool == false