---

- name: "CURL | Install dependencies (Debian)"
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - curl
  when: ansible_os_family == "Debian"

- name: "CURL | Install dependencies (Fedora)"
  dnf:
    name: "{{ item }}"
    state: installed
  with_items:
    - curl
  when: ansible_distribution == "Fedora"

- name: "CURL | Install dependencies (RedHat)"
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - curl
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"