---

- name: "CURL | Install (CentOS)"
  yum:
    name: curl
    state: present
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution == "CentOS"

- name: "CURL | Install (Debian)"
  apt:
    name: curl
    state: present
  when: ansible_os_family == "Debian"

- name: "CURL | Install (RedHat)"
  dnf:
    name: curl
    state: present
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "CentOS"
